#!/bin/bash

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf `pwd`/.vimrc ~/.vimrc

# vimballs
for v in vba/*; do
	ex $v -c UseVimball -c q
done

# plugins & colors
for d in plugin doc colors autoload nerdtree_plugin after ftplugin snippets syntax; do
	mkdir -pv ~/.vim/$d
	cp -rv $d/* ~/.vim/$d
done

copy_files() {
	cd $1
	for d in *; do
		if [ -d $d ]; then
			mkdir -pv ~/.vim/$d
			cp -vr $d/* ~/.vim/$d/
		fi
	done
	cd ..
}

git_pull() {
	DIR=${1/#*\/}
	DIR=${DIR/%.git/}

	if [ ! -d $DIR ]; then
		git clone $2
	fi
	cd $DIR || exit 1
	git pull
	cd ..
}

git_install() {
	DIR=${1/#*\/}
	DIR=${DIR/%.git/}

	git_pull $DIR $1
	copy_files $DIR
}

# Snippets for snipMate
git_pull git://github.com/junegunn/snipmate-snippets.git
cd snipmate-snippets
rake deploy_local
cd ..

# Scala support
git_install git://github.com/junegunn/scala-vim-support.git

# Coffeescript
git_install https://github.com/kchmck/vim-coffee-script.git

# Rails
git_install https://github.com/tpope/vim-rails

# Supertab
git_install https://github.com/ervandew/supertab.git

# endwise
git_install https://github.com/tpope/vim-endwise.git

# fugitive
git_install https://github.com/tpope/vim-fugitive.git

# helptags
ex -c "helptags $HOME/.vim/doc" -c "q"

