#!/bin/bash

cd $(dirname $BASH_SOURCE)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl -fL -o ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf `pwd`/.vimrc ~/.vimrc

for d in ftplugin syntax; do
  if [ -d $d ]; then
    mkdir -pv ~/.vim/$d
    cp -rv $d/* ~/.vim/$d
  fi
done

vim +BundleParallelUpdate +qall

# VimClojure-client
rm -rf vimclojure-nailgun-client*                                            &&
wget http://kotka.de/projects/vimclojure/vimclojure-nailgun-client-2.3.5.zip &&
unzip vimclojure-nailgun-client-2.3.5.zip                                    &&
cd vimclojure-nailgun-client/                                                &&
make                                                                         &&
mkdir -p ~/bin                                                               &&
cp ng ~/bin                                                                  &&
cd -

