#!/bin/bash

# For Vundle behind proxy
export GIT_SSL_NO_VERIFY=true

VUNDLE_DIR=~/.vim/bundle/vundle
if [ -d $VUNDLE_DIR ]; then
  cd $VUNDLE_DIR
  git pull
  cd -
else
  git clone https://github.com/gmarik/vundle.git $VUNDLE_DIR
fi

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf `pwd`/.vimrc ~/.vimrc

for d in *; do
  if [ -d $d ]; then
    mkdir -pv ~/.vim/$d
    cp -rv $d/* ~/.vim/$d
  fi
done

vim +BundleInstall +qall
ex -c "helptags $HOME/.vim/doc" -c "q"
